### ISSUE TITLE
include zip and unzip in docker

### ISSUE THREAD

**Issue by si458** [minostauros/tinyfilemanager-docker#1]
Is it possible for you to include zip and unzip in the docker image?

This would allow the zip function to work!

**Comment by minostauros** [comment]
Thanks for suggestion. Added with 1e3083fa79e26c7161b9a2c9b9aa23e2d4b89534

**Comment by si458** [comment]
Thanks, however that didn’t seem to work?
Keep getting error “Operations with archives are not available”
I think php is missing the zip module from looks of source code of php file
but it can be installed with following
`RUN apk add libzip-dev && docker-php-ext-install zip`

**Comment by si458** [comment]
found from website:

> Fileinfo, iconv, zip, tar and mbstring extensions are strongly recommended.

php modules currently only show iconv,tar and mbstring included, 
so it’s just missing the other 2 which can be installed by the `docker-php-ext-install` command :)

**Comment by si458** [comment]
LEGEND!!!
Have a beer on me! 
all works fine now apart from tar issue but will open another issue for that
