### ISSUE TITLE
Create a master docker tag

### ISSUE THREAD

**Issue by si458** [minostauros/tinyfilemanager-docker#2]
Is is possible for you to create a master docker tag build?
But instead of setting the branch to a certain version just use his master branch?
Only reason I ask is because his master branch has a fix for tar archives but he hasn’t realised a new version yet

**Comment by minostauros** [comment]
Please check nightly tag at [Docker Hub](https://hub.docker.com/r/tigerdockermediocore/tinyfilemanager-docker/tags)

**Comment by si458** [comment]
thank you so much! perfect!
just what i was looking for!
have another beer on me again!

**Comment by si458** [comment]
the nightly build hasnt seen to of run with the latest security fixes,
any chance of running it manually?
or it running itself once a night after a commit has been done during the day?

**Comment by minostauros** [comment]
I'm not maintaining the repo anymore, but you can re-build the nightly tag image by sending a POST to [this url](https://hub.docker.com/api/build/v1/source/a1df6543-c9d7-48ce-bd48-8fbd9f5966bd/trigger/14b92d54-d953-4b21-9a44-96e6cd46fbc6/call/).

**Comment by minostauros** [comment]
I'm not maintaining the repo anymore, but I built the nightly tag after you left the comment and once more yesterday. Check it out!

**Comment by si458** [comment]
brilliant thank you! will check it out :)
