### ISSUE TITLE
not showing /data folder instead shows /app/tinyfilemanager folder?

### ISSUE THREAD

**Issue by si458** [minostauros/tinyfilemanager-docker#4]
im not sure whats happened but for some reason,
when you run the latest image now and map the `/data` folder to say `/home/simon`
its now showing all the contents of `/app/tinyfilemanager` folder like the tinyfilemanager.php and not the contents of `/data`

**Comment by Cediddi** [comment]
this is a real bummer. config.php should be mountable as well as the default directory.

**Comment by FireDrunk** [comment]
@minostauros The bug is in:
https://github.com/minostauros/tinyfilemanager-docker/blob/master/Dockerfile#L13

This should do the replace in config.php.
I think tinyfilemanager.php contains the defaults, and config.php contains the overrides. Hence the $root_path in config.php wins.
